apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: myapi:1.0   # Push to registry if needed
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapi-service
spec:
  type: NodePort
  selector:
    app: myapi
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080