apiVersion: v1
kind: Service
metadata:
  name: myapi-service
spec:
  type: NodePort
  selector:
    app: myapi
  ports:
  - port: 80         # Service port inside cluster
    targetPort: 80   # Container port
    nodePort: 30080  # Port exposed on each node (must be 30000-32767)
